-- Generated by nwg-displays on 2026-09-17 at 22:36:00. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1680x1050@60.0",
    position = "0x0",
    scale = 0.9999999999999992,
    vrr = 0
})
